todoproject/todoapp/urls.py
from . import views
from django.urls import path, include
app_name = 'todoapp'

urlpatterns = [
    path('',views.home,name='home'),
    path('delete/<int:id>/', views.delete, name='delete'),
    path('edit/<int:id>/', views.edit, name='edit'),
    path('cbvhome/', views.tasklistview.as_view(), name='cbvhome'),
    path('cbvdetail/<int:pk>/', views.taskdetailview.as_view(), name='cbvdetail'),
    path('cbvupdate/<int:pk>/', views.taskupdateview.as_view(), name='cbvupdate'),
    path('cbvdelete/<int:pk>/', views.taskdeleteview.as_view(), name='cbvdelete'),
]

todoproject/todoproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todoapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todoproject/todoapp/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    task = models.CharField(max_length=150)
    prio = models.IntegerField()
    date = models.DateField()

    def __str__(self):
        return self.task

todoproject/todoapp/forms.py
from .models import Task
from django import forms


class todoform(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['task', 'prio', 'date']

todoproject/todoapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from .models import Task
from .forms import todoform
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, DeleteView
# Create your views here.

class tasklistview(ListView):
    model = Task
    template_name = 'home.html'
    context_object_name = 'task'

class taskdetailview(DetailView):
    model = Task
    template_name = 'details.html'
    context_object_name = 'task'

class taskupdateview(UpdateView):
    model = Task
    template_name = 'update.html'
    context_object_name = 'task'
    fields = ('task','prio','date')

    def get_success_url(self):
        return reverse('todoapp:cbvdetail', kwargs={'pk': self.object.id})

class taskdeleteview(DeleteView):
    model = Task
    template_name = 'delete.html'
    success_url = reverse_lazy('todoapp:cbvhome')


def home(request):
    tasklist = Task.objects.all()
    if request.method == 'POST':
        name=request.POST.get('taskname','')
        priority = request.POST.get('taskprio','')
        date = request.POST.get('taskdate','')
        add_task = Task(task=name,prio=priority, date=date)
        add_task.save()
        return redirect('/')

    return render(request,'home.html',{'task':tasklist})

def delete(request, id):
    deltask = Task.objects.get(id=id)
    if request.method == 'POST':
        deltask.delete()
        return redirect('/')
    return render(request, 'delete.html',{'tsk':deltask})

def edit(request, id):
    tosk = Task.objects.get(id=id)
    fo = todoform(request.POST or None, instance=tosk)
    if fo.is_valid():
        fo.save()
        return redirect('/')
    return render(request, 'edit.html', {'form': fo, 'task':tosk})

todoproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body class="">
{% block content %}

{% endblock %}
</body>
</html>

todoproject/templates/delete.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    <h4>Completed the {{tsk.task}} task?</h4> <br>
    <input type="submit" name="sub">
</form>
{% endblock %}

todoproject/templates/details.html
{% extends 'base.html' %}
{% block content %}

  <div class="card shadow mb-3 ">
                <div class="card-body">
                    <h5 class="card-title">{{task.task}}</h5>
                    <p><b> Priority:</b> {{task.prio}}</p>
                    <p><b>Date:</b> {{task.date}}</p>
                    <a class="btn btn-danger" href="{% url 'todoapp:delete' task.id %}">Done</a>
                    <a class="btn btn-warning" href="{% url 'todoapp:edit' task.id %}">Edit</a>
                </div>
            </div>

{% endblock %}

todoproject/templates/edit.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" name="con">Confirm</button>
</form>

{% endblock %}

todoproject/templates/home.html
{% extends 'base.html' %}
{% block content %}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner">
                <div class="banner-text">
                    <h1>TODO LIST</h1>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-6 mt-2">
            <h3>Add new tasks:</h3>
            <form action="" method="POST" class="p-3 shadow ">
                {% csrf_token %}
                <div class="form-group  ">
                    <input type="text" class="form-control" name="taskname" placeholder="Name of task">
                </div>
                <div class="form-group">
                    <input type="text" class="form-control" name="taskprio" placeholder="Priority of task">
                </div>
                <div class="form-group">
                    <input type="date" class="form-control" name="taskdate" placeholder="Priority of task">
                </div>
                <div class="form-group ">
                    <input type="submit" class="btn btn-success">
                </div>
            </form>
        </div>
        <div class="col-md-6 mt-2">
            <h3>Task to be completed:</h3>
            {% for i in task %}
            <div class="card shadow mb-3 ">
                <div class="card-body">
                    <h5 class="card-title">{{i.task}}</h5>
                    <p><b> Priority:</b> {{i.prio}}</p>
                    <p><b>Date:</b> {{i.date}}</p>
                    <a class="btn btn-danger" href="{% url 'todoapp:delete' i.id %}">Done</a>
                    <a class="btn btn-warning" href="{% url 'todoapp:edit' i.id %}">Edit</a>
                </div>
            </div>
            {% endfor %}
        </div>

    </div>
</div>

{% endblock %}

todoproject/templates/update.html
{% extends 'base.html' %}
{% block content %}

<div class="card">
    <div class="card-header">
        <div class="card-title">
            Task Update
        </div>
        <div class="card-body">
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit" name="con">Confirm</button>
            </form>
        </div>
    </div>
</div>



{% endblock %}